# Generated by Django 3.2.12 on 2022-04-10 15:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20220410_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='grade',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)], verbose_name='Класс для которого предназначена категория'),
        ),
    ]
