# Generated by Django 3.2.12 on 2022-04-17 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20220417_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourse',
            name='anonymous_user',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Тег для анонимного юзера'),
        ),
    ]
