# Generated by Django 3.2.12 on 2022-04-17 11:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_auto_20220417_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionoption',
            name='value',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Баллы за ответ'),
        ),
    ]
