# Generated by Django 3.2.12 on 2022-04-17 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_auto_20220417_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='course.category', verbose_name='Курс к которому относится материал'),
            preserve_default=False,
        ),
    ]
