# Generated by Django 3.2.12 on 2022-04-18 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_alter_questionoption_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswer',
            name='attempt_counter',
            field=models.IntegerField(default=0, help_text='Увеличивается при каждой попытке ответить на вопрос', verbose_name='Попытка ответить на этот вопрос'),
        ),
    ]
