# Generated by Django 3.2.12 on 2022-04-20 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_image_image'),
        ('course', '0013_questionanswer_attempt_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='images',
            field=models.ManyToManyField(blank=True, to='api.Image', verbose_name='Изображении'),
        ),
    ]
