# Generated by Django 3.2.12 on 2022-04-20 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0014_lecture_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='LecturePassed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время последнего изменения')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.lecture', verbose_name='Пройденная лекция')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passed_lectures', to=settings.AUTH_USER_MODEL, verbose_name='Прошедший пользователь')),
            ],
            options={
                'verbose_name': 'Пройденная лекция',
                'verbose_name_plural': 'Пройденные лекции',
            },
        ),
    ]
