# Generated by Django 3.2.12 on 2022-04-20 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0015_lecturepassed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LecturePassed',
        ),
    ]
