# Generated by Django 3.2.12 on 2022-04-21 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0016_delete_lecturepassed'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время последнего изменения')),
                ('result', models.IntegerField(default=0, verbose_name='Результат')),
                ('question', models.ManyToManyField(blank=True, to='course.Question', verbose_name='Вопросы')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multitests', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь для которого тест')),
            ],
            options={
                'verbose_name': 'Мультитест',
                'verbose_name_plural': 'Мультитесты',
                'ordering': ('-created_at',),
            },
        ),
    ]
