# Generated by Django 3.2.12 on 2022-04-21 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0017_multitest'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswer',
            name='multitest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.multitest', verbose_name='Мультитест'),
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='type',
            field=models.CharField(default='TEST', max_length=50, verbose_name='Тип ответа'),
        ),
    ]
