# Generated by Django 3.2.12 on 2022-05-17 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0018_auto_20220421_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionanswer',
            name='type',
            field=models.CharField(choices=[('MULTITEST', 'MULTITEST'), ('TEST', 'TEST')], default='TEST', max_length=50, verbose_name='Тип ответа'),
        ),
    ]
