# Generated by Django 3.2.12 on 2022-05-17 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0019_alter_questionanswer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='multitest',
            name='is_finished',
            field=models.BooleanField(default=False, verbose_name='Закончен?'),
        ),
    ]
