# Generated by Django 3.2.12 on 2022-05-18 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0020_multitest_is_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Описание вопроса'),
        ),
    ]
