# Generated by Django 3.2.12 on 2022-04-19 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autho', '0003_auto_20220417_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=50, null=True, unique=True, verbose_name='Рабочая почта'),
        ),
    ]
