# Generated by Django 3.2.12 on 2022-04-20 16:12

import autho.services
import autho.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autho', '0006_alter_account_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=autho.services.avatar_upload, validators=[autho.validators.validate_image], verbose_name='Аватар'),
        ),
    ]
