# Generated by Django 3.2.12 on 2022-04-20 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autho', '0007_alter_account_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tokenlog',
            options={'verbose_name': 'Токен', 'verbose_name_plural': 'Токены'},
        ),
    ]
