# Generated by Django 3.2.12 on 2022-04-20 18:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autho', '0009_auto_20220420_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='passed_lectures',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None, verbose_name='Id пройденных курсов'),
        ),
    ]
