# Generated by Django 3.2.12 on 2022-04-20 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время последнего изменения')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок чата')),
                ('text', models.CharField(max_length=1000, verbose_name='Текст чата')),
            ],
            options={
                'verbose_name': 'Чат',
                'verbose_name_plural': 'Чаты',
            },
        ),
        migrations.CreateModel(
            name='ConversationAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время последнего изменения')),
                ('text', models.CharField(max_length=1000, verbose_name='Текст ответа')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='support.conversation', verbose_name='Чат, на которую отвечает')),
            ],
            options={
                'verbose_name': 'Ответ на беседу',
                'verbose_name_plural': 'Ответы на беседы',
            },
        ),
    ]
