OK = 0
BAD_REQUEST = 1
TOKEN_INVALID = 2
MISSING_REQUIRED_PARAMS = 3
CSRF_INVALID = 4
STRIPE_ERROR = 5
INCORRECT_HTTP_METHOD = 6
LIMIT_EXCEED = 7
SUBSCRIPTION_EXPIRED = 8
USER_NOT_FOUND = 9
UPGRADE_TO_PREMIUM = 10
POPUP_ERROR = 11
DIALOG_ERROR = 12
DATA_FORMAT_ERROR = 15
FRAUD_DETECTED = 16

SERVER_ERROR = 999
SUCCESS = 200
