CORRECT = 'CORRECT'
WRONG = 'WRONG'

CORRECT_ANSWER_TEXT = 'Ответ правильный!'
WRONG_ANSWER_TEXT = 'Попробуйте ещё раз!'

ANSWER_CHOICES = (
    (CORRECT, CORRECT),
    (WRONG, WRONG)
)

ANSWER_TEXT_CHOICES = (
    (CORRECT_ANSWER_TEXT, CORRECT_ANSWER_TEXT),
    (WRONG_ANSWER_TEXT, WRONG_ANSWER_TEXT)
)

