# Generated by Django 3.2.12 on 2022-04-21 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.services
import utils.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный?')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание достижении')),
                ('type', models.CharField(choices=[('MULTI_TEST', 'MULTI_TEST')], max_length=50, verbose_name='Тип достижения')),
                ('show_text', models.CharField(max_length=200, verbose_name='Текст при достижении')),
                ('min_points', models.IntegerField(default=50, verbose_name='Минимальные баллы для достижения')),
                ('prize', models.FileField(upload_to=utils.services.prize_upload, validators=[utils.validators.validate_pdf], verbose_name='Приз')),
            ],
            options={
                'verbose_name': 'Достижение',
                'verbose_name_plural': 'Достижении',
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время последнего изменения')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='achievement.achievement', verbose_name='Достижение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Достижение пользователя',
                'verbose_name_plural': 'Достижении пользователей',
            },
        ),
    ]
